steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/backed-nugaskuy/nugaskuy-be-node', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/backed-nugaskuy/nugaskuy-be-node']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'nugaskuy-be-node', '--image', 'gcr.io/backed-nugaskuy/nugaskuy-be-node', '--platform', 'managed', '--region', 'asia-southeast2', '--allow-unauthenticated', '--port', '8000']

images:
  - 'gcr.io/backed-nugaskuy/nugaskuy-be-node'
